import type { DayData } from './data';

export const DAYS2: DayData[] = [
  // ── DAY 5 ──────────────────────────────────────────────────────────────────
  {
    dayNum: 5, order: 5,
    date: "Monday, May 18",
    label: "Day 5",
    focus: "North Coast Guided Tour (Yehliu, Shifen, Jiufen)",
    notes: "GetYourGuide tour — check voucher for exact pickup point (usually Taipei Main Station East Gate 3).",
    events: [
      {
        order: 0, time: "8:45 AM", emoji: "🚌",
        title: "GetYourGuide Tour Pickup",
        description: "Meet the tour bus. Check voucher for exact meeting point — usually Taipei Main Station East Gate 3.",
        location: "Taipei Main Station — East Gate 3 (verify on voucher)",
        transit: "MRT Green Line from Songshan → Taipei Main Station (2 stops). Follow signs to East Gate Exit 3.",
        tips: "Be there 10 min early. Look for the guide holding a sign. Bring cash for lanterns and snacks.",
        checklist: [
          { label: "Check voucher for exact meeting point", done: false, order: 0 },
          { label: "Bring cash for lanterns + snacks", done: false, order: 1 },
          { label: "Arrive Taipei Main Station by 8:35 AM", done: false, order: 2 },
        ],
      },
      {
        order: 1, time: "Morning", emoji: "🪨",
        title: "Yehliu Geopark",
        description: "See the famous Queen's Head rock and the alien-like geological formations along the ocean.",
        location: "Yehliu Geopark, New Taipei City — north coast",
        transit: "Tour bus from Taipei (~1h)",
        tips: "Queen's Head is the most photographed formation — get there before tour buses pile in. Wear sun protection; it is fully exposed by the ocean.",
        checklist: [
          { label: "Photo at Queen's Head rock", done: false, order: 0 },
          { label: "Explore alien formations along the coast", done: false, order: 1 },
        ],
      },
      {
        order: 2, time: "Afternoon", emoji: "🏮",
        title: "Shifen Waterfall & Old Street — Sky Lanterns",
        description: "Write your wishes on a giant sky lantern and release it over the train tracks on Shifen Old Street.",
        location: "Shifen Old Street, Pingxi District, New Taipei City",
        transit: "Tour bus from Yehliu",
        tips: "Lanterns cost about NT$150–200. The vendor paints the colors for luck. Hold steady when releasing — there are active train tracks.",
        checklist: [
          { label: "Release sky lanterns on the tracks", done: false, order: 0 },
          { label: "Walk Shifen Old Street", done: false, order: 1 },
          { label: "See Shifen Waterfall (Taiwan's widest waterfall)", done: false, order: 2 },
        ],
      },
      {
        order: 3, time: "Late Afternoon", emoji: "🍵",
        title: "Jiufen Old Street",
        description: "Spirited Away atmosphere. Narrow alleys, red lanterns, tea houses. One of Taiwan's most iconic spots.",
        location: "Jiufen Old Street, New Taipei City",
        transit: "Tour bus from Shifen",
        tips: "A-Mei Tea House (阿妹茶樓) is the one that inspired Spirited Away — get tea and the view. The alley gets very crowded; go up the steps and explore the side alleys.",
        checklist: [
          { label: "Tea at A-Mei Tea House (Spirited Away inspiration)", done: false, order: 0 },
          { label: "Walk the red lantern alley", done: false, order: 1 },
          { label: "Taro balls dessert", done: false, order: 2 },
        ],
      },
      {
        order: 4, time: "6:00 PM", emoji: "🌆",
        title: "Tour Bus Returns to Taipei",
        description: "Dropped back near Taipei Main Station.",
        location: "Taipei Main Station area",
        transit: "MRT or taxi back to amba Songshan",
        tips: "",
        checklist: [],
      },
    ],
  },

  // ── DAY 6 ──────────────────────────────────────────────────────────────────
  {
    dayNum: 6, order: 6,
    date: "Tuesday, May 19",
    label: "Day 6",
    focus: "Old Taipei, Anime Shopping & A Joy Buffet (Again!)",
    fakeFocus: "Old Taipei, Anime Shopping & Night Out",
    notes: "Skipping lunch to save stomach space for A Joy Buffet at 6 PM.",
    events: [
      {
        order: 0, time: "9:00 AM", emoji: "🥣",
        title: "'The 10 Tastings' Private Food Tour",
        description: "Fuel up on braised pork rice, scallion pancakes, and local bites. This is breakfast AND lunch — skip eating in the afternoon.",
        location: "Meets in central Taipei (check booking confirmation)",
        transit: "Check booking for exact meeting point",
        tips: "Wear comfortable shoes. Bring small cash for tips. This covers your food calories for the afternoon — save room for tonight.",
        checklist: [
          { label: "Check booking confirmation for meeting point", done: false, order: 0 },
          { label: "Braised pork rice (lu rou fan)", done: false, order: 1 },
          { label: "Scallion pancake", done: false, order: 2 },
        ],
      },
      {
        order: 1, time: "1:30 PM", emoji: "🧱",
        title: "Dihua Street (Dadaocheng — Old Taipei)",
        description: "Walk off the food tour in Old Taipei. Grab dried mango and bamboo crafts from the historic shophouses.",
        location: "Dihua Street (迪化街), Datong District",
        transit: "MRT or taxi from food tour end point",
        tips: "This is the oldest street in Taipei. Beautiful Baroque-era facades. Good for dried fruits, teas, and traditional crafts.",
        checklist: [
          { label: "Dried mango from street vendor", done: false, order: 0 },
          { label: "Browse bamboo / traditional crafts", done: false, order: 1 },
        ],
      },
      {
        order: 2, time: "3:00 PM", emoji: "🛍️",
        title: "Ximending — The Harajuku of Taipei",
        description: "Pure geek and pop culture shopping district. Hit: Wan Nian Building (retro claw machines, gachapon, secondhand figures), Taipei Animate (official Japanese manga/merch), Pop Mart Flagship (4-story designer toys), Magfreak (cheap keychains/badges on top floor). Also nearby: MANY Stationery (multi-story stationery paradise — MT washi tapes, POSCA pens, affordable prices; passport discount over NT$500) and ChiuTa Stationery (basement warehouse feel, great for Pilot/Uni-ball refills and unique Taiwanese office supplies).",
        location: "Ximending District (西門町), Wanhua District",
        transit: "MRT Bannan Blue Line to Ximen Station (Exit 6). Walk into the pedestrian zone.",
        tips: "Wan Nian Building is a multi-story retro mall — best for Frieren or Nichijou figures secondhand. Magfreak top floor has the cheapest badges and keychains. MANY Stationery opens at 11 AM — bring your passport for a discount on purchases over NT$500. ChiuTa opens at 10:30 AM and is basement-level with a local wholesale vibe.",
        checklist: [
          { label: "Wan Nian Building — claw machines + figures", done: false, order: 0 },
          { label: "Taipei Animate — official manga/merch", done: false, order: 1 },
          { label: "Pop Mart Flagship — blind boxes", done: false, order: 2 },
          { label: "Magfreak top floor — keychains/badges", done: false, order: 3 },
          { label: "MANY Stationery — washi tapes, POSCA pens (bring passport for discount)", done: false, order: 4 },
          { label: "ChiuTa Stationery — Pilot/Uni-ball refills, Taiwanese supplies", done: false, order: 5 },
        ],
      },
      {
        order: 3, time: "4:30 PM", emoji: "🏨",
        title: "Return to Hotel — Get Dressed",
        description: "MRT Green Line direct from Ximen Station to Songshan Station — 15 min, no transfers. Shower and get dressed up for dinner.",
        location: "amba Taipei Songshan",
        transit: "MRT Green Line: Ximen → Songshan Station. Direct, 15 min, trains every 3–8 min.",
        tips: "The Green Line stops at Ximen — just tap in and ride 5 stops to Songshan. Hotel connected to station.",
        realOnly: true,
        checklist: [
          { label: "Shower and change into dinner attire", done: false, order: 0 },
        ],
      },
      {
        order: 4, time: "6:00–9:30 PM", emoji: "🥂",
        title: "A Joy Buffet — 3 Michelin Stars (Taipei 101, 86F)",
        description: "The highest buffet in Taiwan. Sunset AND nighttime city views from the 86th floor.",
        location: "A Joy Buffet, 86F Taipei 101, Xinyi District",
        transit: "Uber or MRT Red Line to Taipei 101/World Trade Center Station.",
        tips: "Arrive at 5:50 PM. This is the sunset sitting — you will see the city transform from gold to lights. Eat everything.",
        realOnly: true,
        checklist: [
          { label: "Arrive by 5:50 PM", done: false, order: 0 },
          { label: "Watch sunset from 86F", done: false, order: 1 },
        ],
      },
    ],
  },

  // ── DAY 7 ──────────────────────────────────────────────────────────────────
  {
    dayNum: 7, order: 7,
    date: "Wednesday, May 20",
    label: "Day 7",
    focus: "Animal Café, Gundam Base & Tech Mall",
    notes: "Paws Forest requires a reservation — confirm in advance.",
    events: [
      {
        order: 0, time: "8:30 AM", emoji: "🍽️",
        title: "Breakfast",
        description: "Grab breakfast near the hotel before heading out.",
        location: "Near amba Songshan or CityLink Songshan",
        transit: "",
        tips: "CityLink mall attached to hotel has a convenience store and some cafes.",
        checklist: [],
      },
      {
        order: 1, time: "1:30 PM", emoji: "🥢",
        title: "Lunch — Zhongshan Area",
        description: "Shin Yeh Taiwanese Cuisine or a nearby cafe.",
        location: "Zhongshan District, Taipei",
        transit: "MRT Green Line from Songshan → Zhongshan Station (1 stop)",
        tips: "Shin Yeh is a classic Taiwanese restaurant — great for a sit-down lunch with local classics.",
        checklist: [],
      },
      {
        order: 2, time: "2:00 PM", emoji: "🐾",
        title: "Paws Forest (肉球森林) — Reservation Required",
        description: "Interactive animal café with toucans, meerkats, and cats.",
        location: "Paws Forest (肉球森林), Zhongshan District",
        transit: "Short walk or taxi from Zhongshan Station",
        tips: "Reservation is critical — book in advance. Follow all animal interaction rules posted inside.",
        checklist: [
          { label: "Confirm reservation for Paws Forest", done: false, order: 0 },
          { label: "Meet the toucans", done: false, order: 1 },
          { label: "Meet the meerkats", done: false, order: 2 },
        ],
      },
      {
        order: 3, time: "4:30 PM", emoji: "🎮",
        title: "Syntrend Creative Park",
        description: "12-story 'Tech & Anime' mall. Must-see: ROG Flagship (1F), Gundam Base (6F), Gachapon Halls.",
        location: "Syntrend Creative Park (三創生活), Zhongzheng District",
        transit: "MRT Red Line to Zhongxiao Xinsheng Station, Exit 2. Walk ~5 min.",
        tips: "ROG Flagship on 1F has gaming gear. Gundam Base on 6F has every grade of Gunpla. Gachapon halls scattered throughout — bring coins.",
        checklist: [
          { label: "ROG Flagship Store (1F)", done: false, order: 0 },
          { label: "Gundam Base (6F)", done: false, order: 1 },
          { label: "Gachapon halls", done: false, order: 2 },
        ],
      },
      {
        order: 4, time: "6:30 PM", emoji: "🍜",
        title: "Dinner — Syntrend Basement",
        description: "Food court and restaurants in the basement level of Syntrend.",
        location: "Syntrend Creative Park Basement, Zhongzheng District",
        transit: "In building",
        tips: "",
        checklist: [],
      },
    ],
  },

  // ── DAY 8 ──────────────────────────────────────────────────────────────────
  {
    dayNum: 8, order: 8,
    date: "Thursday, May 21",
    label: "Day 8",
    focus: "Hot Springs & Tamsui Sunset",
    notes: "Fu Hang Soy Milk line is notoriously long — get there early to make hot spring reservation at 11 AM.",
    events: [
      {
        order: 0, time: "8:00 AM", emoji: "🚆",
        title: "Transit to Fu Hang Soy Milk",
        description: "Take MRT Green Line from Songshan → Ximen, transfer to Blue Line, 2 stops to Shandao Temple Station, use Exit 5.",
        location: "Songshan MRT Station → Shandao Temple Station",
        transit: "Step 1: Hotel elevator down to Songshan MRT Station. Step 2: MRT Green Line toward Ximen. Step 3: At Ximen, transfer to Blue Line (Bannan Line) heading toward Nangang. Step 4: Ride 2 stops to Shandao Temple Station. Step 5: Use Exit 5.",
        tips: "Green Line → Blue Line transfer is at Ximen Station — well-signed. Takes about 15 min total.",
        checklist: [],
      },
      {
        order: 1, time: "8:30 AM", emoji: "🥣",
        title: "Fu Hang Soy Milk (阜杭豆漿)",
        description: "Order the Xian Dou Jiang (Salty Soy Milk). The line wraps around the building — get here early.",
        location: "Fu Hang Soy Milk (阜杭豆漿), 108 Zhongxiao East Rd, Zhongzheng District — above Shandao Temple Station",
        transit: "Take Exit 5 from Shandao Temple Station, walk up to 2F of the market building",
        tips: "Order: Xian Dou Jiang (salty soy milk), shao bing (sesame flatbread), you tiao (fried dough). Get there before 8:30 AM if possible.",
        checklist: [
          { label: "Xian Dou Jiang (Salty Soy Milk)", done: false, order: 0 },
          { label: "Shao Bing + You Tiao", done: false, order: 1 },
        ],
      },
      {
        order: 2, time: "11:00 AM", emoji: "♨️",
        title: "Grand View Resort Beitou — Private Hot Spring",
        description: "90-min private hot spring room. NT$2,500. Reservation ID: 5DUJE9.",
        location: "Grand View Resort Beitou (北投麗禧溫泉酒店)\nB2, No. 30, Youya Road\nBeitou District, Taipei City, Taiwan (R.O.C.)",
        transit: "MRT Red Line from Shandao Temple → Xinbeitou (end of branch line). Transfer at Beitou Station to the pink Xinbeitou branch line — 1 stop. Or taxi from central Taipei (~NT$400).",
        tips: "Reservation ID: 5DUJE9. Phone: 02 2898 8888. Email: rsvn@gvrb.com.tw. Bring flip flops. Do not eat heavily before.",
        checklist: [
          { label: "Reservation confirmed (ID: 5DUJE9)", done: false, order: 0 },
          { label: "Bring flip flops", done: false, order: 1 },
          { label: "Check in 10 min early", done: false, order: 2 },
        ],
      },
      {
        order: 3, time: "12:30 PM", emoji: "🌡️",
        title: "Walk to Thermal Valley (地熱谷)",
        description: "Famous blue-green boiling sulfur pool — free to view, eerie and beautiful.",
        location: "Thermal Valley (地熱谷), Beitou District",
        transit: "Short walk (~10 min) from Grand View Resort up toward the hills",
        tips: "Do not touch the water — it is nearly 100°C. Free entry. Spend 15–20 min.",
        checklist: [
          { label: "Photo at Thermal Valley", done: false, order: 0 },
        ],
      },
      {
        order: 4, time: "3:00 PM", emoji: "🚆",
        title: "Transit to Tamsui",
        description: "From Thermal Valley: walk to Xinbeitou Station → pink branch line 1 stop to Beitou → transfer to MRT Red Line north → ride to Tamsui (end of line).",
        location: "Xinbeitou Station → Beitou → Tamsui",
        transit: "Step 1: Walk to Xinbeitou Station (~5 min). Step 2: Pink branch line 1 stop to Beitou Station. Step 3: Transfer to Red Line heading north. Step 4: Ride to Tamsui Station (end of line). Total ~30 min.",
        tips: "Red Line to Tamsui runs frequently. Enjoy the above-ground coastal views near the end.",
        checklist: [],
      },
      {
        order: 5, time: "3:30 PM", emoji: "🌅",
        title: "Tamsui Old Street & Sunset",
        description: "Eat Ah-Gei (stuffed tofu) on Old Street. Take the ferry to Fisherman's Wharf and walk Lover's Bridge at sunset.",
        location: "Tamsui Old Street (淡水老街), then Fisherman's Wharf",
        transit: "Walk from Tamsui MRT Station. Ferry to Fisherman's Wharf departs near Tamsui Station ferry pier — NT$50, ~15 min.",
        tips: "Ah-Gei is Tamsui's most famous snack — tofu stuffed with glass noodles in a savory sauce. Lover's Bridge is best at sunset with the mountains in the background.",
        checklist: [
          { label: "Ah-Gei stuffed tofu on Old Street", done: false, order: 0 },
          { label: "Ferry to Fisherman's Wharf", done: false, order: 1 },
          { label: "Sunset at Lover's Bridge", done: false, order: 2 },
        ],
      },
      {
        order: 6, time: "6:00 PM", emoji: "🌉",
        title: "Return to Taipei — Last Shopping",
        description: "MRT Red Line from Tamsui → Zhongshan (~40 min), transfer to Green Line → Songshan (~10 min). Last chance shopping at CityLink Songshan (mall attached to hotel).",
        location: "Tamsui Station → Songshan Station",
        transit: "MRT Red Line: Tamsui → Zhongshan Station (~40 min, trains every 3–8 min). Transfer at Zhongshan to Green Line → Songshan Station (~10 min). Total ~55 min.",
        tips: "CityLink Songshan is in the hotel building — convenient for last-minute souvenirs.",
        checklist: [
          { label: "Last shopping at CityLink Songshan", done: false, order: 0 },
          { label: "Pack for departure tomorrow", done: false, order: 1 },
        ],
      },
    ],
  },

  // ── DAY 9 ──────────────────────────────────────────────────────────────────
  {
    dayNum: 9, order: 9,
    date: "Friday, May 22",
    label: "Day 9",
    focus: "Departure Day",
    notes: "Delta flight departs 9:35 AM. Leave hotel by 6:30 AM.",
    events: [
      {
        order: 0, time: "6:30 AM", emoji: "🚕",
        title: "Taxi to Taoyuan Airport (TPE)",
        description: "Pre-book a taxi or Uber the night before. Ride is ~45 min.",
        location: "amba Taipei Songshan → Taoyuan International Airport (TPE)",
        transit: "Taxi or Uber — about NT$1,200–1,500, ~45 min. Pre-book the night before.",
        tips: "Book the taxi tonight. Leave no later than 6:30 AM for a 9:35 AM flight. Check in 2+ hours early.",
        checklist: [
          { label: "Book taxi/Uber night before", done: false, order: 0 },
          { label: "Check out of hotel", done: false, order: 1 },
          { label: "All bags packed and loaded", done: false, order: 2 },
        ],
      },
      {
        order: 1, time: "9:35 AM", emoji: "✈️",
        title: "Flight Departs — Delta",
        description: "Goodbye Taiwan! 再見！",
        location: "Taoyuan International Airport (TPE)",
        transit: "Delta flight home",
        tips: "Duty-free shopping in TPE is excellent — pineapple cakes, tea, and cosmetics.",
        checklist: [
          { label: "Pineapple cakes from duty free", done: false, order: 0 },
          { label: "Taiwanese tea from duty free", done: false, order: 1 },
        ],
      },
    ],
  },
];
